class OrderType:
    CALL='CALL'
    PUT='PUT'
    BUY='BUY'
    SELL='SELL'

class PositionType:
    LONG = "LONG"
    SHORT = "SHORT"
    SHORT_OPTION = "PUT"
    LONG_OPTION = "CALL"

class StrategyGenerationType:
    PERCENTAGE = "PERCENTAGE"
    SET_VALUE = "SET_VALUE"


class PriceGoalChangeType:
    ASSET_SET_PRICE = 'ASSET_SET_PRICE'
    ASSET_POINTS = 'ASSET_POINTS'
    ASSET_PERCENTAGE = 'ASSET_PERCENTAGE'
    OPTION_TICK = 'OPTION_TICK'
    OPTION_PERCENTAGE = 'OPTION_PERCENTAGE'
    OPTION_SET_PRICE = 'OPTION_SET_PRICE'


class Timespan:
    HOUR = "hour"
    MINUTE = "minute"
    DAY = "day"

class TimespanMultiplier:
    ONE = "1"
    FIFTEEN = "15"
    THIRTY = "30"

class ValidationType:
    SMA = 'sma'
    MACD = 'macd'
    DMI = 'dmi'
    ADX = 'adx'
    RSI = 'rsi'
    VALIDATION_OFF = 'validation off'

class StrategyType:

    LONG_CALL = "LONG_CALL"
    LONG_PUT = "LONG_PUT"
    LONG_STRADDLE = "LONG_STRADDLE"
    LONG_STRANGLE = "LONG_STRANGLE"
    COLLAR = "COLLAR"
    SHORT_PUT = "SHORT_PUT"
    SHORT_CALL = "SHORT_CALL"
    SHORT_STRANGLE = "SHORT_STRANGLE"
    SHORT_STRADDLE = "SHORT_STRADDLE"
    LONG_CALL_SPREAD = "LONG_CALL_SPREAD"
    SHORT_CALL_SPREAD = "SHORT_CALL_SPREAD"
    LONG_PUT_SPREAD = "LONG_PUT_SPREAD"
    SHORT_PUT_SPREAD = "SHORT_PUT_SPREAD"
    IRON_BUTTERFLY = "IRON_BUTTERFLY"
    IRON_CONDOR = "IRON_CONDOR"

class AlertType:
    RSI_OVERBOUGHT = "RSI_OVERBOUGHT"
    RSI_OVERSOLD = "RSI_OVERSOLD"
    RSI_NORMAL = "RSI_NORMAL"
    MACD_SIGNAL_CROSS_MACD ='MACD_SIGNAL_CROSS_MACD'
    MACD_MACD_CROSS_SIGNAL = 'MACD_MACD_CROSS_SIGNAL'
    SMA_CONFIRMATION_UPWARD = 'SMA_CONFIRMATION_UPWARD'
    SMA_CONFIRMATION_DOWNWARD = 'SMA_CONFIRMATION_DOWNWARD'
    DMIPLUS_CROSSOVER_DMINEG= 'DMIPLUS_CROSSOVER_DMINEG'
    DMINEG_CROSSOVER_DMIPLUS = 'DMINEG_CROSSOVER_DMIPLUS'
    ADX_THRESHOLD_UPWARD = 'ADX_THRESHOLD_UPWARD'
    GOLDEN_CROSS_APPEARED = 'GOLDEN_CROSS_APPEARED'
    DEATH_CROSS_APPEARED = 'DEATH_CROSS_APPEARED'
    SUPPORT_RESISTANCE_CONSOLIDATON = 'SUPPORT_RESISTANCE_CONSOLIDATON'
    SUPPORT_RESISTANCE_BREAKOUT_UP = 'SUPPORT_RESISTANCE_BREAKOUT_UP'
    SUPPORT_RESISTANCE_BREAKOUT_DOWN = 'SUPPORT_RESISTANCE_BREAKOUT_DOWN'
    STOCHASTIC_RSI_OVERSOLD = "STOCHASTIC_RSI_OVERSOLD"
    STOCHASTIC_RSI_NORMAL = "STOCHASTIC_RSI_NORMAL"
    STOCHASTIC_RSI_OVERBOUGHT = "STOCHASTIC_RSI_OVERBOUGHT"
    ABOVE_HIGHEST_SR_BAND = 'ABOVE_HIGHEST_SR_BAND'
    BELOW_LOWEST_SR_BAND = 'BELOW_LOWEST_SR_BAND'
    ADX_REVERSAL_BULLISH = 'ADX_REVERSAL_BULLISH'
    ADX_REVERSAL_BEARISH = 'ADX_REVERSAL_BEARISH'
    ADX_REVERSAL_ALTERNATIVE_BULLISH = 'ADX_REVERSAL_ALTERNATIVE_BULLISH'
    ADX_REVERSAL_ALTERNATIVE_BEARISH = 'ADX_REVERSAL_ALTERNATIVE_BEARISH'
    ADX_CROSSOVER_BULLISH = "ADX_CROSSOVER_BULLISH"
    ADX_CROSSOVER_BEARISH = "ADX_CROSSOVER_BEARISH"
    BREAKOUT_LONGTERM_CROSSOVER_BULLISH = 'BREAKOUT_LONGTERM_CROSSOVER_BULLISH'
    BREAKOUT_LONGTERM_CROSSOVER_BEARISH = 'BREAKOUT_LONGTERM_CROSSOVER_BEARISH'
    BREAKOUT_PREDICT_CROSSOVER_BULLISH = 'BREAKOUT_PREDICT_CROSSOVER_BULLISH'
    BREAKOUT_PREDICT_CROSSOVER_BEARISH = 'BREAKOUT_PREDICT_CROSSOVER_BEARISH'
    BREAKOUT_CROSSOVER_BULLISH = 'BREAKOUT_CROSSOVER_BULLISH'
    BREAKOUT_CROSSOVER_BEARISH = 'BREAKOUT_CROSSOVER_BEARISH'
    CURRENT_BREAKOUT_CROSSOVER_BULLISH = "CURRENT_BREAKOUT_CROSSOVER_BULLISH"
    CURRENT_BREAKOUT_CROSSOVER_BEARISH = "CURRENT_BREAKOUT_CROSSOVER_BEARISH"
    VIX_RSI_OVERBOUGHT = "VIX_RSI_OVERBOUGHT"
    VIX_RSI_OVERSOLD = "VIX_RSI_OVERSOLD"
    VIX_RSI_NORMAL = "VIX_RSI_NORMAL"
    VIX_SUPPORT_RESISTANCE_CONSOLIDATION = "VIX_SUPPORT_RESISTANCE_CONSOLIDATION"
    VIX_SUPPORT_RESISTANCE_BREAKOUT_UP = "VIX_SUPPORT_RESISTANCE_BREAKOUT_UP"
    VIX_SUPPORT_RESISTANCE_BREAKOUT_DOWN = "VIX_SUPPORT_RESISTANCE_BREAKOUT_DOWN"
    VIX_SMA_CONFIRMATION_UPWARD = 'SMA_CONFIRMATION_UPWARD'
    VIX_SMA_CONFIRMATION_DOWNWARD = 'SMA_CONFIRMATION_DOWNWARD'
    EXTREME_RSI_OVERBOUGHT = "EXTREME_RSI_OVERBOUGHT"
    EXTREME_RSI_OVERSOLD = "EXTREME_RSI_OVERSOLD"
    EXTREME_RSI_ALTERNATIVE_OVERBOUGHT = "EXTREME_RSI_OVERBOUGHT"
    EXTREME_RSI_ALTERNATIVE_OVERSOLD = "EXTREME_RSI_OVERSOLD"
    MOMENTUM_QUICK_CROSSOVER_BULLISH = "MOMENTUM_QUICK_CROSSOVER_BULLISH"
    MOMENTUM_QUICK_CROSSOVER_BEARISH = "MOMENTUM_QUICK_CROSSOVER_BEARISH"
    RSI_REVERSAL_CROSSOVER_BULLISH = "RSI_REVERSAL_CROSSOVER_BULLISH"
    RSI_REVERSAL_CROSSOVER_BEARISH = "RSI_REVERSAL_CROSSOVER_BEARISH"
    # ABOVE_UPPER_SR_BAND = 'ABOVE_UPPER_SR_BAND'
    # BELOW_LOWER_SR_BAND = 'BELOW_LOWER_SR_BAND'
class Indicator:
    MACD = 'MACD'
    SMA = 'SMA'
    RSI = 'RSI'
    ADX = 'ADX'
    ADX_CROSSOVER = 'ADX_CROSSOVER'
    DMI = 'DMI'
    GOLDEN_CROSS = 'GOLDEN_CROSS'
    DEATH_CROSS = 'DEATH_CROSS'
    PROFITABLE_LINE = 'PROFITABLE_LINE'
    ADX_REVERSAL = 'ADX_REVERSAL'
    ADX_REVERSAL_ALTERNATIVE = 'ADX_REVERSAL_ALTERNATIVE'
    BREAKOUT = 'BREAKOUT'
    BREAKOUT_LONGTERM = 'BREAKOUT_LONGTERM'
    BREAKOUT_PREDICT = 'BREAKOUT_PREDICT'
    SUPPORT_RESISTANCE = 'SUPPORT_RESISTANCE'
    VIX_RSI = "VIX_RSI"
    VIX_SMA = "VIX_SMA"
    VIX_SUPPORT_RESISTANCE = "VIX_SUPPORT_RESISTANCE"
    STOCHASTIC_RSI = "STOCHASTIC_RSI"
    CURRENT_BREAKOUT = "CURRENT_BREAKOUT"
    EXTREME_RSI = "EXTREME_RSI"
    MOMENTUM_QUICK = "MOMENTUM_QUICK"
    EXTREME_RSI_ALTERNATIVE = "EXTREME_RSI_ALTERNATIVE"
    RSI_REVERSAL = "RSI_REVERSAL"
class InventoryFunctionTypes:
    LOAD = "LOAD"
    DID_ALERT = "DID_ALERT"
    DETERMINE_ALERT_TYPE = "DETERMINE_ALERT_TYPE"
    IGNORE = "IGNORE"
    USE_N1_BARS="USE_N1_BARS"
strategy_type_dict ={
    PositionType.LONG:{
        StrategyType.LONG_CALL,
        StrategyType.SHORT_PUT
    },
    PositionType.SHORT:{
        StrategyType.LONG_PUT,
        StrategyType.SHORT_CALL

    }
}


strategy_types= [
    StrategyType.LONG_PUT,
    StrategyType.LONG_PUT,
    StrategyType.LONG_CALL_SPREAD,
    StrategyType.LONG_PUT_SPREAD,
    StrategyType.IRON_BUTTERFLY,
    StrategyType.IRON_CONDOR,
    StrategyType.LONG_STRANGLE,
    StrategyType.LONG_STRADDLE,
    StrategyType.COLLAR,
    StrategyType.SHORT_CALL,
    StrategyType.SHORT_PUT,
    StrategyType.SHORT_PUT_SPREAD,
    StrategyType.SHORT_CALL_SPREAD,
    StrategyType.SHORT_STRANGLE,
    StrategyType.SHORT_STRADDLE

]
validation_types = [
    ValidationType.ADX,
    ValidationType.DMI,
    ValidationType.RSI,
    ValidationType.SMA,
    ValidationType.MACD

]
position_types = [
    PositionType.LONG,
    PositionType.SHORT
]


alert_types=  [
    AlertType.RSI_OVERBOUGHT, AlertType.RSI_OVERSOLD, #rsi
    AlertType.SMA_CONFIRMATION_UPWARD, AlertType.SMA_CONFIRMATION_DOWNWARD, #sma
    AlertType.ADX_THRESHOLD_UPWARD, AlertType.DMINEG_CROSSOVER_DMIPLUS, AlertType.DMIPLUS_CROSSOVER_DMINEG, #adx, dmi
    AlertType.MACD_SIGNAL_CROSS_MACD, AlertType.MACD_MACD_CROSS_SIGNAL, #macd
    AlertType.SUPPORT_RESISTANCE_BREAKOUT_DOWN, AlertType.SUPPORT_RESISTANCE_BREAKOUT_UP, AlertType.SUPPORT_RESISTANCE_CONSOLIDATON, AlertType.BELOW_LOWEST_SR_BAND, AlertType.ABOVE_HIGHEST_SR_BAND, #sr bands
    AlertType.GOLDEN_CROSS_APPEARED, AlertType.DEATH_CROSS_APPEARED, #crosses
    AlertType.ADX_REVERSAL_BEARISH, AlertType.ADX_REVERSAL_BULLISH #crosses


]